#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <tuple>
#include <vector>
struct Bar{long long t;double o,h,l,c,v;};
struct Row{Bar b;double e9=0,e21=0,atr=0,rsi=50,rv=0,vwap=0;};
struct Param{double rv,hi,gap,rr;};
struct Stat{int n=0,w=0;double sum=0,pf=0,dd=0,med=0;};
static long long iso(const std::string&s){std::tm t{};int y,M,d,h,m,q=0;if(std::sscanf(s.c_str(),"%d-%d-%dT%d:%d:%d",&y,&M,&d,&h,&m,&q)<5)return 0;t.tm_year=y-1900;t.tm_mon=M-1;t.tm_mday=d;t.tm_hour=h;t.tm_min=m;t.tm_sec=q;return timegm(&t);}
struct NY{int y,mo,d,h,mi;};
static NY ny(long long z){time_t t=z;std::tm x{};const char*old=getenv("TZ");std::string save=old?old:"";setenv("TZ","America/New_York",1);tzset();localtime_r(&t,&x);if(save.empty())unsetenv("TZ");else setenv("TZ",save.c_str(),1);tzset();return{x.tm_year+1900,x.tm_mon+1,x.tm_mday,x.tm_hour,x.tm_min};}
static long long day(NY x){return 10000LL*x.y+100*x.mo+x.d;}
static std::vector<Bar> load(const std::string&p){std::vector<Bar>v;std::string cmd="gzip -dc \""+p+"\"";FILE*f=popen(cmd.c_str(),"r");if(!f)return v;char z[8192];bool head=true;while(fgets(z,sizeof z,f)){if(head){head=false;continue;}std::stringstream ss(z);std::string a;std::vector<std::string>c;while(std::getline(ss,a,','))c.push_back(a);if(c.size()<6)continue;try{Bar b{iso(c[0]),stod(c[1]),stod(c[2]),stod(c[3]),stod(c[4]),stod(c[5])};if(b.t&&b.o>0&&b.h>0&&b.l>0&&b.c>0)v.push_back(b);}catch(...){}}pclose(f);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.t<b.t;});v.erase(std::unique(v.begin(),v.end(),[](auto&a,auto&b){return a.t==b.t;}),v.end());return v;}
static std::vector<Bar> agg(const std::vector<Bar>&a){std::vector<Bar>o;long long last=0;for(auto b:a){auto x=ny(b.t);if(x.h<9||x.h>15||(x.h==9&&x.mi<30))continue;int m=x.h*60+x.mi-570;if(m<0||m>=390)continue;long long k=day(x)*1000+m/3;if(o.empty()||last!=k){o.push_back({b.t,b.o,b.h,b.l,b.c,b.v});last=k;}else{auto&q=o.back();q.h=std::max(q.h,b.h);q.l=std::min(q.l,b.l);q.c=b.c;q.v+=b.v;}}return o;}
static std::vector<Row> indicators(const std::vector<Bar>&d){std::vector<Row>r(d.size());for(size_t i=0;i<d.size();++i){r[i].b=d[i];r[i].e9=i?r[i-1].e9*.8+d[i].c*.2:d[i].c;r[i].e21=i?r[i-1].e21*(20.0/22)+d[i].c*(2.0/22):d[i].c;if(i>=13){for(size_t j=i-13;j<=i;++j){double pc=j?d[j-1].c:d[j].c;r[i].atr+=std::max({d[j].h-d[j].l,std::fabs(d[j].h-pc),std::fabs(d[j].l-pc)});}r[i].atr/=14;}if(i>=14){double u=0,n=0;for(size_t j=i-13;j<=i;++j){double q=d[j].c-d[j-1].c;u+=std::max(0.0,q);n+=std::max(0.0,-q);}r[i].rsi=n?100-100/(1+u/n):100;}if(i>=19){double vv=0;for(size_t j=i-19;j<=i;++j)vv+=d[j].v;r[i].rv=(vv/20)>0?d[i].v/(vv/20):0;}auto x=ny(d[i].t);double pv=0,vv=0;for(size_t j=i;;--j){if(day(ny(d[j].t))!=day(x))break;pv+=d[j].c*d[j].v;vv+=d[j].v;if(j==0)break;}r[i].vwap=vv?pv/vv:d[i].c;}return r;}
static std::vector<double> sim(const std::vector<Row>&d,Param p){std::vector<double>o;for(size_t i=30;i+1<d.size();){auto&r=d[i];if(!(r.e9>r.e21&&r.rv>=p.rv&&r.b.c>d[i-1].b.h&&r.b.c>r.vwap&&r.rsi>=50&&r.rsi<=p.hi&&(r.b.c-r.e9)<=p.gap*r.atr)){++i;continue;}double en=d[i+1].b.o,st=std::max(r.b.l,en-1.2*r.atr),risk=en-st;if(risk<=0||risk/en>.012){++i;continue;}double tg=en+p.rr*risk,ex=en;size_t j=i+1,e=std::min(d.size()-1,i+10);for(;j<=e;++j){if(d[j].b.l<=st){ex=st;break;}if(d[j].b.h>=tg){ex=tg;break;}if(j==e)ex=d[j].b.c;}o.push_back((ex/en-1)*100-.04);i=j+1;}return o;}
static Stat score(const std::vector<double>&v){Stat s;s.n=v.size();if(v.empty())return s;double gw=0,gl=0,eq=0,pk=0;auto x=v;for(double q:v){s.sum+=q;if(q>0){s.w++;gw+=q;}else gl-=q;eq+=q;pk=std::max(pk,eq);s.dd=std::min(s.dd,eq-pk);}std::sort(x.begin(),x.end());s.med=x[x.size()/2];s.pf=gl?gw/gl:0;return s;}
static bool better(const Stat&a,const Stat&b){return std::tie(a.pf,a.w,a.sum)>std::tie(b.pf,b.w,b.sum);}
static std::string n(double x,int p){std::ostringstream o;o<<std::fixed<<std::setprecision(p)<<x;return o.str();}
static std::string run(const std::string&s,const std::string&dir,int minD){auto d=indicators(agg(load(dir+"/"+s+".csv.gz")));if(d.empty())return "{\"available\":false}";std::vector<long long>days;for(auto&r:d){auto k=day(ny(r.b.t));if(days.empty()||days.back()!=k)days.push_back(k);}std::ostringstream o;o<<"{\"available\":true,\"days\":"<<days.size()<<",\"bars_3m\":"<<d.size();if((int)days.size()<minD)return o.str()+",\"note\":\"need at least "+std::to_string(minD)+" days\"}";size_t cut=(size_t)(days.size()*.7)-1;long long cd=days[cut];std::vector<Row>tr,te;for(auto&r:d)(day(ny(r.b.t))<=cd?tr:te).push_back(r);Param bp{1.2,65,.6,1};Stat bs;for(double rv:{1.2,1.4,1.5,1.7,2.0})for(double hi:{65,70,75})for(double gap:{0.6,0.8,1.0,1.2})for(double rr:{1.0,1.2,1.5,2.0}){Param p{rv,hi,gap,rr};auto z=score(sim(tr,p));if(z.n>=20&&better(z,bs)){bs=z;bp=p;}}auto teS=score(sim(te,bp));auto out=[&](Stat z){std::ostringstream q;q<<"{\"trades\":"<<z.n<<",\"win_rate_pct\":"<<n(z.n?100.0*z.w/z.n:0,2)<<",\"avg_ret_pct\":"<<n(z.n?z.sum/z.n:0,4)<<",\"median_ret_pct\":"<<n(z.med,4)<<",\"profit_factor\":"<<n(z.pf,3)<<",\"total_ret_pct\":"<<n(z.sum,3)<<",\"max_drawdown_pct\":"<<n(z.dd,3)<<"}";return q.str();};o<<",\"train_days\":"<<cut+1<<",\"test_days\":"<<days.size()-cut-1<<",\"optimized_params\":{\"rvol\":"<<bp.rv<<",\"rsi_hi\":"<<bp.hi<<",\"atr_gap\":"<<bp.gap<<",\"stop_atr\":1.2,\"rr\":"<<bp.rr<<",\"max_risk_pct\":0.012},\"train\":"<<out(bs)<<",\"test\":"<<out(teS)<<"}";return o.str();}
int main(int argc,char**argv){std::string dir="data/toss_1m",out="research/backtest_toss_v5_result.json",syms="NVDA,AMD,INTC,SOXL,SOXS,TQQQ";int minD=100;for(int i=1;i<argc;i++){std::string a=argv[i];if(a=="--data"&&i+1<argc)dir=argv[++i];else if(a=="--out"&&i+1<argc)out=argv[++i];else if(a=="--symbols"&&i+1<argc)syms=argv[++i];else if(a=="--min-days"&&i+1<argc)minD=atoi(argv[++i]);}std::ofstream f(out);f<<"{\"engine\":\"C++17\",\"source\":\"Toss historical 1m\",\"symbols\":{";std::stringstream ss(syms);std::string s;bool first=true;while(std::getline(ss,s,',')){if(!first)f<<",";first=false;f<<"\""<<s<<"\":"<<run(s,dir,minD);}f<<"}}\n";}